services:
  frontend:
    build:
      context: ../..
      dockerfile: infra/local/frontend.Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ../../client:/app
      - /app/node_modules
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ../..
      dockerfile: infra/local/backend.Dockerfile
    ports:
      - "7071:7071"
    volumes:
      - ../../api:/home/site/wwwroot
      - /home/site/wwwroot/node_modules
    command: bash -c "npm run build && npm run watch & func start --javascript --port 7071 --watch"
    environment:
      - AzureWebJobsStorage=UseDevelopmentStorage=true
      - FUNCTIONS_WORKER_RUNTIME=node
      - FUNCTIONS_INPROC_NET8_ENABLED=1
