services:
  frontend:
    build:
      context: ../..
      dockerfile: infra/prod/frontend.Dockerfile
    ports:
      - "80:80"

  backend:
    build:
      context: ../..
      dockerfile: infra/prod/backend.Dockerfile
    environment:
      - AzureWebJobsStorage=UseDevelopmentStorage=true
      - FUNCTIONS_WORKER_RUNTIME=node
      - FUNCTIONS_INPROC_NET8_ENABLED=1
    ports:
      - "7071:80"
